"""
batch_report.py
===============
Summary report generator for batch (parametric) beam analysis.
"""

from datetime import datetime
from pathlib import Path
from typing import Union
import pandas as pd


class BatchReportGenerator:
    """
    Generate summary markdown reports for batch analysis.
    """
    def __init__(self, solver):
        self.solver = solver
        self.summary = solver.batch_summary

    def generate_report(self, output_path: Union[str, Path]) -> str:
        output_path = str(output_path)

        # Calculate Envelope
        # For each numeric column, find the absolute maximum and its associated row values
        numeric_cols = ['max_deflection', 'max_shear', 'max_moment', 'max_von_mises', 'sf']
        envelope_data = {'case_name': '**ENVELOPE (ABS MAX)**'}

        for col in numeric_cols:
            if col in self.summary.columns:
                if col == 'sf':
                    # For Safety Factors, the envelope is the MINIMUM (most critical)
                    crit_idx = self.summary[col].idxmin()
                else:
                    # For loads and deflections, it is the absolute maximum
                    crit_idx = self.summary[col].abs().idxmax()

                envelope_data[col] = self.summary.loc[crit_idx, col]
                # Try to copy associated location/ply if they exist
                for suffix in ['_x', '_y', '_z', '_ply']:
                    loc_col = col.replace('max_', 'max_vm_') if 'von_mises' in col else col + suffix
                    if 'von_mises' in col and suffix == '_x': loc_col = 'max_vm_x'
                    if col == 'sf': loc_col = 'mos'

                    if col == 'max_deflection' and suffix == '_x': loc_col = 'max_deflection_x'
                    if col == 'max_shear' and suffix == '_x': loc_col = 'max_shear_x'
                    if col == 'max_moment' and suffix == '_x': loc_col = 'max_moment_x'

                    if loc_col in self.summary.columns:
                        envelope_data[loc_col] = self.summary.loc[crit_idx, loc_col]

        # Append envelope to a copy of summary for display
        display_df = pd.concat([self.summary, pd.DataFrame([envelope_data])], ignore_index=True)

        title = "# Batch Analysis Summary Report\n\n"
        gen_info = f"**Generated:** {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}\n\n"

        model_info = "## 1. Model Information\n\n"
        model_info += f"- **Nodes:** {self.solver.mesh.num_nodes}\n"
        model_info += f"- **Elements:** {self.solver.mesh.num_elements}\n"
        model_info += f"- **Total Load Cases:** {len(self.summary)}\n\n"

        results_info = "## 2. Analysis Summary\n\n"
        results_info += display_df.to_markdown(index=False)
        results_info += "\n\n---\n*Report generated by Beam FEA Analysis Tool*"

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(title + gen_info + model_info + results_info)

        return output_path
