"""
mesh.py
=======
Mesh generation and management for beam finite element analysis.

Handles node creation, element connectivity, and mesh refinement.
"""

import numpy as np
from typing import Tuple, List, Optional, Union
from dataclasses import dataclass


class Mesh:
    """
    Data-Oriented Finite element mesh for beam structures.
    
    Nodes and elements are stored internally as flat 2D NumPy matrices 
    for maximum computational performance and minimal memory overhead.
    """
    
    def __init__(self):
        """Initialize empty mesh."""
        # Nodes: Shape (N, 2) storing [x, y] coordinates
        self.nodes = np.zeros((0, 2), dtype=float)
        
        # Elements: Shape (E, 2) storing [node1_id, node2_id]
        self.elements = np.zeros((0, 2), dtype=int)
        
        self.waypoint_nodes: List[int] = [] # Node IDs at segment boundaries
        self._elem_starts = None  # Cache for element search
    
    def add_node(self, x: float, y: float) -> int:
        """
        Add a node to the mesh.
        
        Parameters:
        -----------
        x, y : float
            Node coordinates
            
        Returns:
        --------
        node_id : int
            ID of the created node
        """
        node_id = self.nodes.shape[0]
        self.nodes = np.vstack([self.nodes, [x, y]])
        return node_id
    
    def add_element(self, node1: int, node2: int) -> int:
        """
        Add an element to the mesh.
        
        Parameters:
        -----------
        node1, node2 : int
            Node IDs
            
        Returns:
        --------
        element_id : int
            ID of the created element
        """
        if node1 < 0 or node1 >= self.num_nodes:
            raise ValueError(f"Invalid node1 ID: {node1}. Must be between 0 and {self.num_nodes-1}")
        if node2 < 0 or node2 >= self.num_nodes:
            raise ValueError(f"Invalid node2 ID: {node2}. Must be between 0 and {self.num_nodes-1}")
        if node1 == node2:
            raise ValueError(f"Cannot create element with same node at both ends: {node1}")
            
        element_id = self.elements.shape[0]
        self.elements = np.vstack([self.elements, [node1, node2]])
        
        # Invalidate element start cache
        self._elem_starts = None
        
        return element_id
    
    def get_node_coords(self) -> np.ndarray:
        """
        Get all node coordinates as array.
        
        Returns:
        --------
        coords : np.ndarray
            Array of shape (num_nodes, 2) [x, y]
        """
        return self.nodes
    
    def get_connectivity(self) -> np.ndarray:
        """
        Get element connectivity as array.
        
        Returns:
        --------
        connectivity : np.ndarray
            Array of shape (num_elements, 2) [node1, node2]
        """
        return self.elements
    
    @property
    def num_nodes(self) -> int:
        """Number of nodes in mesh."""
        return self.nodes.shape[0]
    
    @property
    def num_elements(self) -> int:
        """Number of elements in mesh."""
        return self.elements.shape[0]
    
    @property
    def num_dofs(self) -> int:
        """Total number of degrees of freedom (3 per node for 2D beam)."""
        return 3 * self.num_nodes
    
    def find_element_at_x(self, x: float) -> int:
        """
        Find the element ID containing the global coordinate x.
        
        Parameters:
        -----------
        x : float
            Global x-coordinate
            
        Returns:
        --------
        element_id : int
            ID of the containing element, or -1 if not found
        """
        if self.num_elements == 0:
            return -1
            
        # Optimization: Binary search for ordered meshes
        # Build or use cached index of element start positions
        if self._elem_starts is None:
            self._elem_starts = self.nodes[self.elements[:, 0], 0]
        
        # Check if elem_starts is roughly sorted (monotone increasing)
        # In most beam meshes generated by our tools, this is true.
        idx = np.searchsorted(self._elem_starts, x, side='right') - 1
        idx = np.clip(idx, 0, self.num_elements - 1)
        
        node1, node2 = self.elements[idx]
        x1, x2 = self.nodes[node1, 0], self.nodes[node2, 0]
        if min(x1, x2) <= x <= max(x1, x2):
            return idx
            
        # Fallback to linear search for irregular/unordered meshes
        for i in range(self.num_elements):
            n1, n2 = self.elements[i]
            x1, x2 = self.nodes[n1, 0], self.nodes[n2, 0]
            if min(x1, x2) <= x <= max(x1, x2):
                return i
        
        # Tolerance check for precision at ends
        x_min, x_max = np.min(self.nodes[:, 0]), np.max(self.nodes[:, 0])
        if abs(x - x_min) < 1e-9: return 0
        if abs(x - x_max) < 1e-9: return self.num_elements - 1
            
        return -1

    def __str__(self):
        return f"Mesh: {self.num_nodes} nodes, {self.num_elements} elements"


    @staticmethod
    def from_path(points: List[Tuple[float, float]],
                  elements_per_segment: Union[int, List[int]],
                  grading_ratios: Optional[Union[float, List[float]]] = None) -> 'Mesh':
        """
        Generate a mesh along a path defined by a series of points.
        
        This is the primary way to create meshes in beam_fea. It handles:
        - Single straight lines (2 points)
        - Piecewise linear paths / Angled frames (multiple points)
        - Multi-span continuous beams
        - Graded elements for local refinement
        """
        if len(points) < 2:
            raise ValueError("Path must have at least 2 points.")

        num_segments = len(points) - 1
        if isinstance(elements_per_segment, int):
            elements_per_segment = [elements_per_segment] * num_segments
            
        if grading_ratios is None:
            grading_ratios = [1.0] * num_segments
        elif isinstance(grading_ratios, float):
            grading_ratios = [grading_ratios] * num_segments

        mesh = Mesh()
        mesh.nodes = np.array([points[0][:2]], dtype=float)
        mesh.waypoint_nodes.append(0)

        for i in range(num_segments):
            # Internal logic for graded segments
            p1 = np.array(points[i][:2], dtype=float)
            p2 = np.array(points[i+1][:2], dtype=float)
            num_elements = elements_per_segment[i]
            ratio = grading_ratios[i]
            
            L_total = np.linalg.norm(p2 - p1)
            direction = (p2 - p1) / L_total if L_total > 0 else np.zeros(2)
            
            if ratio == 1.0:
                t = np.linspace(0, 1, num_elements + 1)
                seg_nodes = p1[None, :] + t[:, None] * (p2 - p1)[None, :]
            else:
                L1 = L_total * (ratio - 1) / (ratio**num_elements - 1)
                positions = np.zeros(num_elements + 1)
                for j in range(1, num_elements + 1):
                    positions[j] = positions[j-1] + L1 * (ratio**(j-1))
                positions *= (L_total / positions[-1])
                seg_nodes = p1[None, :] + direction[None, :] * positions[:, None]
            
            # Assemble into global mesh
            start_num = mesh.nodes.shape[0] - 1
            mesh.nodes = np.vstack([mesh.nodes, seg_nodes[1:]])
            
            new_elems = np.vstack((np.arange(num_elements), np.arange(1, num_elements + 1))).T + start_num
            mesh.elements = np.vstack([mesh.elements, new_elems]) if mesh.elements.size else new_elems
            
            mesh.waypoint_nodes.append(mesh.nodes.shape[0] - 1)

        return mesh

    @staticmethod
    def from_arc(radius: float, start_angle: float, end_angle: float,
                 num_elements: int) -> 'Mesh':
        """Generate a circular arc mesh."""
        if radius <= 0:
            raise ValueError(f"Radius must be positive, got {radius}")
            
        mesh = Mesh()
        theta = np.linspace(np.radians(start_angle), np.radians(end_angle), num_elements + 1)
        
        x = radius * np.cos(theta)
        y = radius * np.sin(theta)
        mesh.nodes = np.column_stack((x, y))
        mesh.elements = np.vstack((np.arange(num_elements), np.arange(1, num_elements + 1))).T
        
        mesh.waypoint_nodes = [0, num_elements]
        return mesh

    def __str__(self):
        return f"Mesh: {self.num_nodes} nodes, {self.num_elements} elements"


class MeshRefinement:
    """Mesh refinement utilities for NumPy Data-Oriented meshes."""
    
    @staticmethod
    def refine_uniform(mesh: 'Mesh', refinement_level: int = 1) -> 'Mesh':
        """
        Uniformly refine mesh by splitting each element vectorized.
        """
        current_mesh = mesh
        
        for _ in range(refinement_level):
            new_mesh = Mesh()
            
            orig_nodes = current_mesh.nodes
            orig_elems = current_mesh.elements
            
            # Midpoints of all original elements
            n1_coords = orig_nodes[orig_elems[:, 0]]
            n2_coords = orig_nodes[orig_elems[:, 1]]
            midpoints = (n1_coords + n2_coords) / 2.0
            
            # New nodes array: append midpoints to the end of original nodes
            new_mesh.nodes = np.vstack([orig_nodes, midpoints])
            
            # Form new elements
            num_orig_nodes = orig_nodes.shape[0]
            num_orig_elems = orig_elems.shape[0]
            
            midnode_ids = np.arange(num_orig_nodes, num_orig_nodes + num_orig_elems)
            
            # Two new elements for each old one:
            # 1. n1 to midnode
            # 2. midnode to n2
            elems_part1 = np.column_stack((orig_elems[:, 0], midnode_ids))
            elems_part2 = np.column_stack((midnode_ids, orig_elems[:, 1]))
            
            # Flatten to shape (2 * E, 2) keeping connectivity order
            new_mesh.elements = np.empty((2 * num_orig_elems, 2), dtype=int)
            new_mesh.elements[0::2] = elems_part1
            new_mesh.elements[1::2] = elems_part2
            
            # Update waypoint IDs if they exist. 
            new_mesh.waypoint_nodes = list(current_mesh.waypoint_nodes)
            
            current_mesh = new_mesh
            
        return current_mesh
    
    @staticmethod
    def get_element_sizes(mesh: Mesh) -> np.ndarray:
        """Calculate euclidian size of each element vectorized."""
        if mesh.num_elements == 0:
            return np.array([])
            
        n1 = mesh.nodes[mesh.elements[:, 0]]
        n2 = mesh.nodes[mesh.elements[:, 1]]
        return np.linalg.norm(n2 - n1, axis=1)


if __name__ == "__main__":
    # Demonstration
    print("\n" + "="*70)
    print("MESH GENERATION EXAMPLES (REFACTORED UNIFIED MESH)")
    print("="*70)
    
    # Example 1: Simple beam
    print("\n1. Simple horizontal beam (from_path):")
    mesh1 = Mesh.from_path([(0, 0), (1000, 0)], elements_per_segment=10)
    print(f"   {mesh1}")
    
    # Example 2: Angled frame
    print("\n2. Angled Frame (from_path):")
    mesh2 = Mesh.from_path([(0, 0), (1000, 0), (1000, 1000)], elements_per_segment=[10, 10])
    print(f"   {mesh2}")
    
    # Example 3: Graded mesh
    print("\n3. Graded mesh (fine at start):")
    mesh3 = Mesh.from_path([(0, 0), (1000, 0)], elements_per_segment=10, grading_ratios=2.0)
    sizes = MeshRefinement.get_element_sizes(mesh3)
    print(f"   {mesh3}")
    print(f"   Element sizes: {sizes[0]:.2f} to {sizes[-1]:.2f} mm")
    
    # Example 4: Curved Beam
    print("\n4. Curved beam (from_arc):")
    mesh4 = Mesh.from_arc(radius=100, start_angle=0, end_angle=90, num_elements=10)
    print(f"   {mesh4}")

