"""
mesh.py
=======
Mesh generation and management for beam finite element analysis.

Handles node creation, element connectivity, and mesh refinement.
"""

import numpy as np
from typing import Tuple, List, Optional, Union
from dataclasses import dataclass


class Mesh:
    """
    Data-Oriented Finite element mesh for beam structures.
    
    Nodes and elements are stored internally as flat 2D NumPy matrices 
    for maximum computational performance and minimal memory overhead.
    """
    
    def __init__(self):
        """Initialize empty mesh."""
        # Nodes: Shape (N, 2) storing [x, y] coordinates
        self.nodes = np.zeros((0, 2), dtype=float)
        
        # Elements: Shape (E, 2) storing [node1_id, node2_id]
        self.elements = np.zeros((0, 2), dtype=int)
        
        self.waypoint_nodes: List[int] = [] # Node IDs at segment boundaries
        self._elem_starts = None  # Cache for element search
    
    def add_node(self, x: float, y: float) -> int:
        """
        Add a node to the mesh.
        
        Parameters:
        -----------
        x, y : float
            Node coordinates
            
        Returns:
        --------
        node_id : int
            ID of the created node
        """
        node_id = self.nodes.shape[0]
        self.nodes = np.vstack([self.nodes, [x, y]])
        return node_id
    
    def add_element(self, node1: int, node2: int) -> int:
        """
        Add an element to the mesh.
        
        Parameters:
        -----------
        node1, node2 : int
            Node IDs
            
        Returns:
        --------
        element_id : int
            ID of the created element
        """
        if node1 < 0 or node1 >= self.num_nodes:
            raise ValueError(f"Invalid node1 ID: {node1}. Must be between 0 and {self.num_nodes-1}")
        if node2 < 0 or node2 >= self.num_nodes:
            raise ValueError(f"Invalid node2 ID: {node2}. Must be between 0 and {self.num_nodes-1}")
        if node1 == node2:
            raise ValueError(f"Cannot create element with same node at both ends: {node1}")
            
        element_id = self.elements.shape[0]
        self.elements = np.vstack([self.elements, [node1, node2]])
        
        # Invalidate element start cache
        self._elem_starts = None
        
        return element_id
    
    def get_node_coords(self) -> np.ndarray:
        """
        Get all node coordinates as array.
        
        Returns:
        --------
        coords : np.ndarray
            Array of shape (num_nodes, 2) [x, y]
        """
        return self.nodes
    
    def get_connectivity(self) -> np.ndarray:
        """
        Get element connectivity as array.
        
        Returns:
        --------
        connectivity : np.ndarray
            Array of shape (num_elements, 2) [node1, node2]
        """
        return self.elements
    
    @property
    def num_nodes(self) -> int:
        """Number of nodes in mesh."""
        return self.nodes.shape[0]
    
    @property
    def num_elements(self) -> int:
        """Number of elements in mesh."""
        return self.elements.shape[0]
    
    @property
    def num_dofs(self) -> int:
        """Total number of degrees of freedom (3 per node for 2D beam)."""
        return 3 * self.num_nodes
    
    def find_element_at_x(self, x: float) -> int:
        """
        Find the element ID containing the global coordinate x.
        
        Parameters:
        -----------
        x : float
            Global x-coordinate
            
        Returns:
        --------
        element_id : int
            ID of the containing element, or -1 if not found
        """
        if self.num_elements == 0:
            return -1
            
        # Optimization: Binary search for ordered meshes
        # Build or use cached index of element start positions
        if self._elem_starts is None:
            self._elem_starts = self.nodes[self.elements[:, 0], 0]
        
        # Check if elem_starts is roughly sorted (monotone increasing)
        # In most beam meshes generated by our tools, this is true.
        idx = np.searchsorted(self._elem_starts, x, side='right') - 1
        idx = np.clip(idx, 0, self.num_elements - 1)
        
        node1, node2 = self.elements[idx]
        x1, x2 = self.nodes[node1, 0], self.nodes[node2, 0]
        if min(x1, x2) <= x <= max(x1, x2):
            return idx
            
        # Fallback to linear search for irregular/unordered meshes
        for i in range(self.num_elements):
            n1, n2 = self.elements[i]
            x1, x2 = self.nodes[n1, 0], self.nodes[n2, 0]
            if min(x1, x2) <= x <= max(x1, x2):
                return i
        
        # Tolerance check for precision at ends
        x_min, x_max = np.min(self.nodes[:, 0]), np.max(self.nodes[:, 0])
        if abs(x - x_min) < 1e-9: return 0
        if abs(x - x_max) < 1e-9: return self.num_elements - 1
            
        return -1

    def __str__(self):
        return f"Mesh: {self.num_nodes} nodes, {self.num_elements} elements"


class MeshGenerator:
    """Utilities for generating finite element meshes."""
    
    @staticmethod
    def line_mesh(start: Tuple[float, float],
                  end: Tuple[float, float],
                  num_elements: int) -> 'Mesh':
        """
        Generate a uniform mesh along a straight line.
        """
        if num_elements < 1:
            raise ValueError(f"Number of elements must be at least 1, got {num_elements}")
            
        mesh = Mesh()
        p1 = np.array(start[:2], dtype=float)
        p2 = np.array(end[:2], dtype=float)

        # Vectorized coordinate generation
        t = np.linspace(0, 1, num_elements + 1)
        mesh.nodes = p1[None, :] + t[:, None] * (p2 - p1)[None, :]
        
        # Vectorized connectivity generation
        mesh.elements = np.vstack((np.arange(num_elements), np.arange(1, num_elements + 1))).T
        mesh.waypoint_nodes = [0, num_elements]
        
        return mesh
    
    @staticmethod
    def beam_mesh_1d(length: float, num_elements: int,
                     orientation: str = 'horizontal') -> 'Mesh':
        """
        Generate a 1D beam mesh (horizontal or vertical).
        DEPRECATED: Use line_mesh((0,0), (L,0), N) instead.
        """
        import warnings
        warnings.warn("beam_mesh_1d is deprecated. Use line_mesh instead.", DeprecationWarning)
        
        if length <= 0:
            raise ValueError(f"Length must be positive, got {length}")
        if num_elements < 1:
            raise ValueError(f"Number of elements must be at least 1, got {num_elements}")
        
        if orientation.lower() == 'horizontal':
            start = (0.0, 0.0)
            end = (length, 0.0)
        elif orientation.lower() == 'vertical':
            start = (0.0, 0.0)
            end = (0.0, length)
        else:
            raise ValueError("Orientation must be 'horizontal' or 'vertical'")
        
        return MeshGenerator.line_mesh(start, end, num_elements)

    
    @staticmethod
    def graded_mesh(start: Tuple[float, float],
                    end: Tuple[float, float],
                    num_elements: int, grading_ratio: float = 1.0) -> 'Mesh':
        mesh = Mesh()
        
        if grading_ratio == 1.0:
            return MeshGenerator.line_mesh(start, end, num_elements)
        
        p1 = np.array(start[:2], dtype=float)
        p2 = np.array(end[:2], dtype=float)

        # Geometric series positioning
        L_total = np.linalg.norm(p2 - p1)
        L1 = L_total * (grading_ratio - 1) / (grading_ratio**num_elements - 1)
        
        positions = np.zeros(num_elements + 1)
        for i in range(1, num_elements + 1):
            positions[i] = positions[i-1] + L1 * (grading_ratio**(i-1))
        
        positions *= (L_total / positions[-1]) # Normalize precision
        direction = (p2 - p1) / L_total
        
        # Vectorized coordinate mapping
        mesh.nodes = p1[None, :] + direction[None, :] * positions[:, None]
        mesh.elements = np.vstack((np.arange(num_elements), np.arange(1, num_elements + 1))).T
        mesh.waypoint_nodes = [0, num_elements]
        
        return mesh
    
    @staticmethod
    def path_mesh(points: List[Tuple[float, float]],
                  elements_per_segment: Union[int, List[int]],
                  grading_ratios: Optional[Union[float, List[float]]] = None) -> 'Mesh':
        if len(points) < 2:
            raise ValueError("Path must have at least 2 points.")

        num_segments = len(points) - 1
        if isinstance(elements_per_segment, int):
            elements_per_segment = [elements_per_segment] * num_segments
            
        if grading_ratios is None:
            grading_ratios = [1.0] * num_segments
        elif isinstance(grading_ratios, float):
            grading_ratios = [grading_ratios] * num_segments

        mesh = Mesh()
        mesh.nodes = np.array([points[0][:2]], dtype=float)
        mesh.waypoint_nodes.append(0)

        for i in range(num_segments):
            seg_mesh = MeshGenerator.graded_mesh(points[i], points[i+1], elements_per_segment[i], grading_ratios[i])
            
            # Assemble native matrices rapidly
            start_num = mesh.nodes.shape[0] - 1
            
            # Append nodes (skip first node of segment to avoid dupes)
            mesh.nodes = np.vstack([mesh.nodes, seg_mesh.nodes[1:]])
            
            # Map elements
            new_elements = seg_mesh.elements + start_num
            mesh.elements = np.vstack([mesh.elements, new_elements]) if mesh.elements.size else new_elements
            
            mesh.waypoint_nodes.append(mesh.nodes.shape[0] - 1)

        return mesh

    @staticmethod
    def multi_span_beam(span_lengths: List[Union[float, Tuple[float, float]]],
                        elements_per_span: List[int],
                        orientation: str = 'horizontal') -> 'Mesh':
        """
        Generate mesh for a multi-span continuous beam.

        Parameters:
        -----------
        span_lengths : list of float or tuple
            If float: Length of each span (mm). Orientation applies.
            If tuple: (dx, dy) relative vector for each span.
        elements_per_span : list of int
            Number of elements in each span.
        orientation : str
            'horizontal' or 'vertical' (only used if span_lengths are floats).

        Returns:
        --------
        mesh : Mesh
            Generated mesh. `mesh.waypoint_nodes` contains support IDs.
        """
        if len(span_lengths) != len(elements_per_span):
            raise ValueError("span_lengths and elements_per_span must have same length")

        # Convert span definitions to waypoints
        points = [(0.0, 0.0)]
        curr_x, curr_y = 0.0, 0.0

        for val in span_lengths:
            if isinstance(val, (int, float)):
                if orientation.lower() == 'horizontal':
                    curr_x += val
                else:
                    curr_y += val
            elif isinstance(val, (tuple, list, np.ndarray)) and len(val) == 2:
                curr_x += val[0]
                curr_y += val[1]
            else:
                raise TypeError(f"Invalid span definition: {val}. Expected float or (dx, dy).")

            points.append((curr_x, curr_y))

        return MeshGenerator.path_mesh(points, elements_per_span)
    
    @staticmethod
    def curved_beam(radius: float, start_angle: float, end_angle: float,
                    num_elements: int) -> 'Mesh':
        if radius <= 0:
            raise ValueError(f"Radius must be positive, got {radius}")
            
        mesh = Mesh()
        theta = np.linspace(np.radians(start_angle), np.radians(end_angle), num_elements + 1)
        
        x = radius * np.cos(theta)
        y = radius * np.sin(theta)
        mesh.nodes = np.column_stack((x, y))
        mesh.elements = np.vstack((np.arange(num_elements), np.arange(1, num_elements + 1))).T
        
        mesh.waypoint_nodes = [0, num_elements]
        return mesh


class MeshRefinement:
    """Mesh refinement utilities for NumPy Data-Oriented meshes."""
    
    @staticmethod
    def refine_uniform(mesh: 'Mesh', refinement_level: int = 1) -> 'Mesh':
        """
        Uniformly refine mesh by splitting each element vectorized.
        """
        current_mesh = mesh
        
        for _ in range(refinement_level):
            new_mesh = Mesh()
            
            orig_nodes = current_mesh.nodes
            orig_elems = current_mesh.elements
            
            # Midpoints of all original elements
            n1_coords = orig_nodes[orig_elems[:, 0]]
            n2_coords = orig_nodes[orig_elems[:, 1]]
            midpoints = (n1_coords + n2_coords) / 2.0
            
            # New nodes array: append midpoints to the end of original nodes
            new_mesh.nodes = np.vstack([orig_nodes, midpoints])
            
            # Form new elements
            num_orig_nodes = orig_nodes.shape[0]
            num_orig_elems = orig_elems.shape[0]
            
            midnode_ids = np.arange(num_orig_nodes, num_orig_nodes + num_orig_elems)
            
            # Two new elements for each old one:
            # 1. n1 to midnode
            # 2. midnode to n2
            elems_part1 = np.column_stack((orig_elems[:, 0], midnode_ids))
            elems_part2 = np.column_stack((midnode_ids, orig_elems[:, 1]))
            
            # Flatten to shape (2 * E, 2) keeping connectivity order
            new_mesh.elements = np.empty((2 * num_orig_elems, 2), dtype=int)
            new_mesh.elements[0::2] = elems_part1
            new_mesh.elements[1::2] = elems_part2
            
            # Update waypoint IDs if they exist. 
            # Note: The structural IDs of original nodes did not change.
            new_mesh.waypoint_nodes = list(current_mesh.waypoint_nodes)
            
            current_mesh = new_mesh
            
        return current_mesh
    
    @staticmethod
    def get_element_sizes(mesh: Mesh) -> np.ndarray:
        """Calculate euclidian size of each element vectorized."""
        if mesh.num_elements == 0:
            return np.array([])
            
        n1 = mesh.nodes[mesh.elements[:, 0]]
        n2 = mesh.nodes[mesh.elements[:, 1]]
        return np.linalg.norm(n2 - n1, axis=1)


if __name__ == "__main__":
    # Demonstration
    print("\n" + "="*70)
    print("MESH GENERATION EXAMPLES (NUMPY BACKEND)")
    print("="*70)
    
    # Example 1: Simple beam
    print("\n1. Simple horizontal beam:")
    mesh1 = MeshGenerator.line_mesh((0,0), (1000,0), num_elements=10)
    print(f"   {mesh1}")
    
    # Example 2: Multi-span beam
    print("\n2. Multi-span continuous beam:")
    mesh2 = MeshGenerator.multi_span_beam(
        span_lengths=[500, 800, 500],
        elements_per_span=[5, 8, 5]
    )
    print(f"   {mesh2}")
    print(f"   Total length: {mesh2.nodes[-1, 0]} mm")
    
    # Example 3: Graded mesh
    print("\n3. Graded mesh (fine at start):")
    mesh3 = MeshGenerator.graded_mesh((0, 0), (1000, 0), num_elements=10, grading_ratio=2.0)
    sizes = MeshRefinement.get_element_sizes(mesh3)
    print(f"   {mesh3}")
    print(f"   Element sizes: {sizes[0]:.2f} to {sizes[-1]:.2f} mm")
    
    # Example 4: Uniform refinement
    print("\n4. Uniform refinement:")
    mesh4 = MeshGenerator.line_mesh((0,0), (100,0), num_elements=5)
    print(f"   Original: {mesh4}")
    mesh4_refined = MeshRefinement.refine_uniform(mesh4, refinement_level=2)
    print(f"   After 2 refinements: {mesh4_refined}")
